[custom]


; ==========================================================
; 节点清洗：剔除机场展示/说明/防失联/流量提示节点
; ==========================================================
exclude=流量|套餐|到期|剩余|重置|官网|网站|最新网址|防失联|失联|官网地址|公告|通知|TG|Telegram|电报|群|频道|说明|使用说明|QQ群|客服|工单|订阅|Expire|Traffic|Reset|Remaining|Official|Website


; 业务分流
; AI
ruleset=🧚 AI,https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs
ruleset=🧚 AI,https://gh-proxy.com/raw.githubusercontent.com/cutethotw/ClashRule/refs/heads/main/Rule/Claude.list
ruleset=🧚 AI,https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
ruleset=🧚 AI,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/cutethotw/ClashRule/refs/heads/main/Rule/AI.yaml
ruleset=🧚 AI,https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/groq.mrs
ruleset=🧚 AI,https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Grok.list
ruleset=🧚 AI,https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list
ruleset=🧚 AI,https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/perplexity.mrs

; TikTok
ruleset=🎶 TikTok,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
ruleset=🎶 TikTok,https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs

; YouTube
ruleset=📹 YouTube,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml

; Netflix
ruleset=🎥 Netflix,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml

; DisneyPlus
ruleset=🐹 DisneyPlus,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml

; PrimeVideo
ruleset=📽️ PrimeVideo,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml

; HBO
ruleset=🎦 HBO,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
ruleset=🎦 HBO,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.yaml
ruleset=🎦 HBO,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.yaml

; AppleTV
ruleset=🍎 AppleTV,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml

; EMBY
ruleset=🎬 EMBY,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Emby.yaml
ruleset=🎬 EMBY,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml

; 巴哈姆特
ruleset=📺 巴哈姆特,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml

; Bilibili
ruleset=📺 Bilibili,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list

; Spotify
ruleset=🎵 Spotify,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml

; 国外媒体
ruleset=🌍 国外媒体,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml


; Google
ruleset=📢 谷歌,https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs
ruleset=📢 谷歌,clash-ipcidr:https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs
ruleset=📢 谷歌,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

; Microsoft
ruleset=Ⓜ️ 微软云盘,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml

; Apple
ruleset=🍎 苹果服务,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml

; Telegram
ruleset=📲 Telegram,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml

; Discord
ruleset=🤖 Discord,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml

; 游戏平台
ruleset=🎮 游戏平台,clash-classic:https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml

; Test
ruleset=🧪 Test,https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list

; 国外
ruleset=🚀 国外流量,https://gh-proxy.com/raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Custom_Proxy.list

; 国内
ruleset=🚀 国外流量,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 国内流量,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 国内流量,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 国内流量,https://gh-proxy.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 国内流量,[]GEOIP,CN,no-resolve

; 其他
ruleset=其他,[]FINAL
ruleset=其他,[]FINAL



;设置分组标志位
custom_proxy_group=🧚 AI`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎶 TikTok`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=📹 YouTube`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎥 Netflix`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🐹 DisneyPlus`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=📽️ PrimeVideo`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎦 HBO`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🍎 AppleTV`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎬 EMBY`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=📺 巴哈姆特`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=📺 Bilibili`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎵 Spotify`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🌍 国外媒体`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🍎 苹果服务`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=📲 Telegram`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🤖 Discord`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎮 游戏平台`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🧪 Test`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🚀 国外流量`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT
custom_proxy_group=🎯 国内流量`[]DIRECT`[]所有-自动`[]所有-手动`[]自建-自动`[]自建-手动`[]香港-自动`[]香港-手动`[]日本-自动`[]日本-手动`[]美国-自动`[]美国-手动`[]其他-自动`[]其他-手动`[]REJECT

custom_proxy_group=所有-手动`select`^((?!(DIRECT|REJECT)).)*$
custom_proxy_group=所有-自动`url-test`^((?!(DIRECT|REJECT)).)*$`https://www.gstatic.com/generate_204`180,50
custom_proxy_group=自建-手动`select`(DMIT-)
custom_proxy_group=自建-自动`url-test`(DMIT-)`https://www.gstatic.com/generate_204`180,50
custom_proxy_group=香港-手动`select`(?=.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong)).*$
custom_proxy_group=香港-自动`url-test`(?=.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong)).*$`https://www.gstatic.com/generate_204`180,50
custom_proxy_group=日本-手动`select`(?=.*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)).*$
custom_proxy_group=日本-自动`url-test`(?=.*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)).*$`https://www.gstatic.com/generate_204`180,50
custom_proxy_group=美国-手动`select`(?=.*(广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).*$
custom_proxy_group=美国-自动`url-test`(?=.*(广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).*$`https://www.gstatic.com/generate_204`180,50
custom_proxy_group=其他-手动`select`^((?!(DIRECT|REJECT|广港|香港|HK|Hong Kong|🇭🇰|HongKong|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).)*$
custom_proxy_group=其他-自动`url-test`^((?!(DIRECT|REJECT|广港|香港|HK|Hong Kong|🇭🇰|HongKong|广台|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).)*$`https://www.gstatic.com/generate_204`180,50


enable_rule_generator=true
overwrite_original_rules=true
